language: java

jdk:
  - openjdk8

install:
  - pip install codecov

script:
  - mvn clean install cobertura:cobertura

after_success:
  - codecov

notifications:
  email:
    on_failure: change
    on_success: change
